Repository jobsgowhere/jobsgowhere, pull requests merged in 2020-09, with the labels that each got.

#131 Implement Update, Delete TalentById
  cmd/jobsgowhere.go
  go.mod
  internal/talent/controller.go
  internal/talent/repository.go
  internal/talent/service.go
Labels: backend

#136 Implement Delete JobPostById
  cmd/jobsgowhere.go
  internal/job/controller.go
  internal/job/repository.go
  internal/job/service.go
Labels: backend

#129 Feature/search api
  cmd/jobsgowhere.go
  internal/job/controller.go
  internal/job/model.go
  internal/job/repository.go
  internal/job/service.go
  internal/talent/controller.go
  internal/talent/model.go
  internal/talent/repository.go
  internal/talent/service.go
Labels: backend

#128 Feature POST for jobs and talents
  ui/package.json
  ui/src/App.tsx
  ui/src/components/FormFields.tsx
  ui/src/screens/NewPost/components/DescriptionField.tsx
  ui/src/screens/NewPost/components/NewPostForm.tsx
  ui/src/screens/NewPost/components/PostTypeField.tsx
  ui/src/screens/NewPost/components/TitleField.tsx
  ui/src/screens/NewPost/machines/NewPostForm.ts
  ui/yarn.lock
Labels: frontend

#143 Fix new post
  ui/src/screens/NewPost/components/Actions.tsx
  ui/src/screens/NewPost/components/NewPostForm.tsx
  ui/src/screens/NewPost/components/PostTypeField.tsx
  ui/src/screens/NewPost/machines/NewPostForm.ts
  ui/src/types.ts
Labels: bug, frontend

#138 Chore tweak input error
  ui/src/components/FormFields.tsx
  ui/src/screens/NewPost/components/DescriptionField.tsx
  ui/src/screens/NewPost/components/NewPostForm.tsx
Labels: chore, frontend

#140 Feature/connect user profile
  ui/src/components/useMessageDialog.tsx
  ui/src/components/useToast.tsx
  ui/src/contexts/Profile.tsx
  ui/src/screens/Profile/ProfileScreen.tsx
  ui/src/screens/Profile/components/Edit.tsx
  ui/src/screens/Profile/components/Summary.tsx
  ui/src/screens/Profile/types.ts
  ui/src/shared/components/PostDetail.tsx
  ui/src/types.ts
Labels: frontend
