Repository jobsgowhere/jobsgowhere, pull requests merged in 2020-10, with the labels that each got.

#144 Remove debug
  ui/src/App.tsx
  ui/src/components/Header/index.tsx
  ui/src/components/Main.tsx
  ui/src/screens/Authorize/AuthorizeScreen.tsx
  ui/src/screens/Home/HomeScreen.tsx
  ui/src/screens/Jobs/JobsScreen.tsx
  ui/src/screens/Talents/TalentsScreen.tsx
Labels: frontend

#151 Chore update posts loading
  ui/.eslintrc.json
  ui/src/components/PostLoader.tsx
  ui/src/screens/Jobs/JobsScreen.tsx
  ui/src/screens/Talents/TalentsScreen.tsx
Labels: chore, frontend

#141 Feature/connect validation
  ui/src/components/FormFields.tsx
  ui/src/components/useMessageDialog.tsx
  ui/src/shared/components/PostDetail.tsx
  ui/src/types.ts
Labels: frontend

#154 Feature nav profile
  ui/package.json
  ui/src/components/Header/UserNav.tsx
  ui/src/components/Menu.tsx
  ui/src/machines/auth0.ts
  ui/src/shared/components/PostDetail.tsx
  ui/yarn.lock
Labels: frontend

#155 Bug modal component
  ui/src/components/Modal.tsx
  ui/src/shared/components/PostDetail.tsx
Labels: bug, frontend

#156 Bug fixes
  ui/src/screens/Authorize/AuthorizeScreen.tsx
  ui/src/screens/Jobs/JobsScreen.tsx
  ui/src/screens/Jobs/hooks/useJobsReducer.ts
  ui/src/screens/Talents/TalentsScreen.tsx
  ui/src/screens/Talents/hooks/useTalentsReducer.ts
  ui/src/shared/components/PostDetailPlaceholder.tsx
Labels: bug, frontend

#153 Add website for Seeker
  internal/talent/model.go
  internal/talent/service.go
Labels: backend

#162 UI updates
  ui/package.json
  ui/src/components/Button.tsx
  ui/src/components/useToast.tsx
  ui/src/screens/Post/components/PostTypeField.tsx
  ui/src/screens/Profile/ProfileScreen.tsx
  ui/src/screens/Profile/components/Edit.tsx
  ui/src/shared/components/Post.tsx
  ui/src/shared/components/PostComponents.tsx
  ui/src/shared/components/PostDetail.tsx
  ui/src/types.ts
  ui/yarn.lock
Labels: bug, chore, frontend

#163 Update NewPost to restrict post type to profile type
  ui/src/screens/Post/components/NewPostForm.tsx
Labels: chore, frontend
