Repository jobsgowhere/jobsgowhere, pull requests merged in 2020-11, with the labels that each got.

#173 Chore: Update regex to enforce URLs require either http/https
  ui/src/screens/Post/components/NewPostForm.tsx
  ui/src/screens/Profile/components/Edit.tsx
Labels: chore, frontend, v1.0

#164 Chore update nav
  ui/src/App.tsx
  ui/src/components/Header/MobileNav.tsx
  ui/src/components/Header/UserNav.tsx
  ui/src/components/Header/index.tsx
  ui/src/components/useMessageDialog.tsx
  ui/src/screens/Profile/components/Edit.tsx
Labels: chore, frontend

#175 Chore intermediate profile
  ui/src/components/Header/CompleteProfile.tsx
  ui/src/components/Header/MobileNav.tsx
  ui/src/components/Header/PlaceholderAvatar.tsx
  ui/src/components/Header/UserNav.tsx
  ui/src/components/Header/index.tsx
  ui/src/shared/components/PostDetail.tsx
Labels: chore, frontend

#176 Update job PostDetail Company Info button label
  ui/src/shared/components/PostComponents.tsx
  ui/src/shared/components/PostDetail.tsx
Labels: bug, frontend

#178 Feature 170 page title
  ui/package.json
  ui/public/index.html
  ui/src/components/Layout.tsx
  ui/src/screens/About/AboutUsScreen.tsx
  ui/src/screens/About/FAQScreen.tsx
  ui/src/screens/Jobs/JobsScreen.tsx
  ui/src/screens/Post/NewPostScreen.tsx
  ui/src/screens/Profile/ProfileScreen.tsx
  ui/src/screens/Profile/components/Edit.tsx
  ui/src/screens/Talents/TalentsScreen.tsx
  ui/src/shared/components/Post.tsx
  ui/src/shared/components/Search.tsx
  ui/yarn.lock
Labels: chore, frontend

#182 Fix unable to exit post detail on talent screen on mobile view
  ui/src/screens/Talents/TalentsScreen.tsx
Labels: bug, frontend

#183 Minor polishes to UI
  ui/src/shared/components/CategorySelector.tsx
  ui/src/shared/components/Search.tsx
Labels: frontend

#184 Chore - Disable email field from editing
  ui/src/screens/Profile/components/Edit.tsx
Labels: frontend

#185 Maintenance
  ui/.vscode/settings.json
  ui/package.json
  ui/src/machines/auth0.ts
  ui/src/screens/About/FAQScreen.tsx
  ui/src/screens/Post/components/NewPostForm.tsx
  ui/src/screens/Profile/components/Edit.tsx
  ui/src/shared/components/PostComponents.tsx
  ui/src/shared/components/PostDetail.tsx
  ui/tsconfig.json
  ui/yarn.lock
Labels: chore, frontend

#187 Fix initial profile creation failing
  ui/src/screens/Profile/components/Edit.tsx
Labels: bug, frontend

#190 Update app name jobshippo on frontend
  ui/.env.development
  ui/.env.production
  ui/public/index.html
  ui/src/components/Footer.tsx
  ui/src/components/Header/index.tsx
  ui/src/components/Layout.tsx
  ui/src/components/Modal.tsx
  ui/src/components/useMessageDialog.tsx
  ui/src/contexts/Profile.tsx
  ui/src/logo.svg
  ui/src/machines/auth0.ts
  ui/src/screens/About/AboutUsScreen.tsx
  ui/src/screens/About/FAQScreen.tsx
  ui/src/screens/Jobs/JobsScreen.tsx
  ui/src/screens/Post/components/NewPostForm.tsx
  ui/src/screens/Profile/components/Edit.tsx
  ui/src/screens/Talents/TalentsScreen.tsx
  ui/src/shared/services/ApiClient.ts
Labels: chore, frontend, v1.0

#192 Implement PostSpinner
  ui/package.json
  ui/src/components/PostSpinner.tsx
  ui/src/screens/Jobs/JobsScreen.tsx
  ui/src/screens/Talents/TalentsScreen.tsx
  ui/src/shared/components/PostsContainer.tsx
  ui/yarn.lock
Labels: frontend, help wanted, v1.0

#196 Fix missing space for job posting headline
  ui/src/shared/components/Post.tsx
Labels: bug, frontend

#199 Update Hirer profile title and company field labels
  ui/src/screens/Profile/components/Edit.tsx
Labels: chore, frontend
