Repository jobsgowhere/jobsgowhere, pull requests merged in 2020-12, with the labels that each got.

#211 Fix twitter meta tags
  ui/public/index.html
  ui/public/static/facebook-share-image.png
Labels: chore, frontend

#209 Auto bold seeking/hiring text of post title
  ui/src/shared/components/Post.tsx
  ui/src/shared/components/PostDetail.tsx
  ui/src/shared/lib/boldSeekingHiring.tsx
Labels: frontend

#210 Chore UI fixes
  ui/src/components/Button.tsx
  ui/src/shared/components/PostDetail.tsx
Labels: chore, frontend

#218 Fix DetailsContainer not scrollable on small viewports
  ui/src/components/Layout.tsx
  ui/src/shared/components/DetailsContainer.tsx
Labels: bug, frontend

#223 Check and set detail view in Layout instead of sub components
  ui/src/components/Header/NavBack.tsx
  ui/src/components/Layout.tsx
  ui/src/screens/Jobs/hooks/useJobsReducer.ts
  ui/src/screens/Talents/hooks/useTalentsReducer.ts
  ui/src/shared/components/Post.tsx
Labels: bug, frontend
